import React from 'react';

// Styles
import './apptext.scss';

export const AppText = () => {
	return (
		<ul className='accordion'>
			<li>
				<input type='radio' name='accordion' id='first' defaultChecked />
				<label htmlFor='first'>EXIF data viewer online</label>
				<div className='content'>
					<p>
						"EXIF Image Data or EXIF Photography Data can be an important source
						of knowledge for discovering how photographers capture images and
						what tools they use in the process. It is a set of photo data that
						describes and gives details about the rights, who created them, when
						and for what, image size, camera or mobile model, lens aperture "f",
						shutter speed "S", ISO sensitivity, GPS data, date and more."
					</p>
				</div>
			</li>
			<li>
				<input type='radio' name='accordion' id='second' />
				<label htmlFor='second'>Metadata viewer online</label>
				<div className='content'>
					<p>
						"Image metadata, or photo metadata, summarizes basic information
						about the image, making it easy to find and work with particular
						instances of data. The metadata can be created manually to be more
						precise or automatically and contain more basic information, for
						example: The name of the author of the image, the copyright of the
						photo, the date of creation of the image, the date of modification
						of the image, the photo and the file size, etc."
					</p>
				</div>
			</li>
			<li>
				<input type='radio' name='accordion' id='third' />
				<label htmlFor='third'>
					XMP data viewer online & AI image detector
				</label>
				<div className='content'>
					<p>
						"The XMP files data store changes made to your image in
						post-processing. Extracted XMP tags are grouped by namespace. Each
						one is separate object in output."
					</p>
					<p>
						"Also, if you want to know if an image was generated by AI, you are
						looking for an online AI image recognition app, or you want to
						detect if a Photography was created by AI, you can use this app,
						because they usually don't have metadata."
					</p>
				</div>
			</li>
			<li>
				<input type='radio' name='accordion' id='fourth' />
				<label htmlFor='fourth'>Instructions</label>
				<div className='content'>
					<p>1.- Select an Image or Photograph.</p>
					<p>
						2.- The app will display the image, EXIF data, metadata and XMP
						data.
					</p>
					<p>3.- Optional: You can go to RESIZE IMAGE link.</p>
				</div>
			</li>
		</ul>
	);
};
